version: "3.9"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8000:8000"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api-server
